import { BarChart3, Cloud, Code2, LineChart, Palette, ShieldCheck } from 'lucide-react';

const progressData = [
  {
    id: 1,
    icon: Code2,
    category: 'Development',
    badgeColor: 'text-blue-600',
    badgeBg: 'bg-blue-50 dark:bg-blue-900/20',
    iconBg: 'bg-blue-100 dark:bg-blue-900/30',
    title: 'Advanced JavaScript Architecture',
    instructor: 'Sarah Williams',
    completion: 75,
    lessonsDone: 12,
    lessonsTotal: 16,
  },
  {
    id: 2,
    icon: Palette,
    category: 'Design',
    badgeColor: 'text-purple-600',
    badgeBg: 'bg-purple-50 dark:bg-purple-900/20',
    iconBg: 'bg-purple-100 dark:bg-purple-900/30',
    title: 'UI/UX Design Masterclass',
    instructor: 'Mike Johnson',
    completion: 45,
    lessonsDone: 9,
    lessonsTotal: 20,
  },
  {
    id: 3,
    icon: LineChart,
    category: 'Business',
    badgeColor: 'text-orange-600',
    badgeBg: 'bg-orange-50 dark:bg-orange-900/20',
    iconBg: 'bg-orange-100 dark:bg-orange-900/30',
    title: 'Data Science Fundamentals',
    instructor: 'David Lee',
    completion: 90,
    lessonsDone: 18,
    lessonsTotal: 20,
  },
  {
    id: 4,
    icon: Cloud,
    category: 'Cloud',
    badgeColor: 'text-cyan-600',
    badgeBg: 'bg-cyan-50 dark:bg-cyan-900/20',
    iconBg: 'bg-cyan-100 dark:bg-cyan-900/30',
    title: 'Cloud Native Bootcamp',
    instructor: 'Priya Nair',
    completion: 60,
    lessonsDone: 12,
    lessonsTotal: 20,
  },
  {
    id: 5,
    icon: ShieldCheck,
    category: 'Security',
    badgeColor: 'text-red-600',
    badgeBg: 'bg-red-50 dark:bg-red-900/20',
    iconBg: 'bg-red-100 dark:bg-red-900/30',
    title: 'Cybersecurity Essentials',
    instructor: 'Alex Chen',
    completion: 35,
    lessonsDone: 7,
    lessonsTotal: 20,
  },
  {
    id: 6,
    icon: BarChart3,
    category: 'Analytics',
    badgeColor: 'text-emerald-600',
    badgeBg: 'bg-emerald-50 dark:bg-emerald-900/20',
    iconBg: 'bg-emerald-100 dark:bg-emerald-900/30',
    title: 'Marketing Analytics Lab',
    instructor: 'Jenna Patel',
    completion: 22,
    lessonsDone: 16,
    lessonsTotal: 20,
  },
  {
    id: 7,
    icon: BarChart3,
    category: 'Analytics',
    badgeColor: 'text-emerald-600',
    badgeBg: 'bg-emerald-50 dark:bg-emerald-900/20',
    iconBg: 'bg-emerald-100 dark:bg-emerald-900/30',
    title: 'Marketing Analytics Lab',
    instructor: 'Jenna Patel',
    completion: 82,
    lessonsDone: 16,
    lessonsTotal: 20,
  },
];

export default progressData;
